
name: Integration test

on:
  workflow_dispatch:
    inputs:
      connectors_version:
        description: 'The version of the connectors to test'
        required: true
        default: 'SNAPSHOT'

defaults:
  run:
    # use bash shell by default to ensure pipefail behavior is the default
    # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

jobs:
  determine-inputs:
    runs-on: ubuntu-latest
    outputs:
      camunda-helm-git-ref: ${{ steps.set_vars.outputs.camunda-helm-git-ref }}
      extra-values-url: ${{ steps.set_vars.outputs.extra-values-url }}
    steps:
      - name: Define version map
        run: |
          if [[ "${{ inputs.connectors_version }}" == 8.3* ]]; then
            echo "Setting variables for 8.3"
            echo "::set-output name=camunda-helm-git-ref::$(echo $VARS_8_3 | jq -r '.camunda-helm-git-ref')"
            echo "::set-output name=extra-values-url::$(echo $VARS_8_3 | jq -r '.extra-values-url')"
          elif [[ "${{ inputs.connectors_version }}" == 8.4* ]]; then
            echo "Setting variables for 8.4"
            echo "::set-output name=camunda-helm-git-ref::$(echo $VARS_8_4 | jq -r '.camunda-helm-git-ref')"
            echo "::set-output name=extra-values-url::$(echo $VARS_8_4 | jq -r '.extra-values-url')"
          elif [[ "${{ inputs.connectors_version }}" == 8.5* ]]; then
            echo "Setting variables for 8.5"
            echo "::set-output name=camunda-helm-git-ref::$(echo $VARS_8_5 | jq -r '.camunda-helm-git-ref')"
            echo "::set-output name=extra-values-url::$(echo $VARS_8_5 | jq -r '.extra-values-url')"
          else
            echo "Version does not match a supported minor version, setting outputs to null"
            echo "::set-output name=camunda-helm-git-ref::null"
            echo "::set-output name=extra-values-url::null"
          fi
        env:
          VARS_8_3: '{"camunda-helm-git-ref": "camunda-platform-8.3", "extra-values-url": "https://raw.githubusercontent.com/camunda/camunda-platform-helm/main/charts/camunda-platform/values/values-v8.3.yaml"}'
          VARS_8_4: '{"camunda-helm-git-ref": "camunda-platform-8.4", "extra-values-url": "https://raw.githubusercontent.com/camunda/camunda-platform-helm/main/charts/camunda-platform/values/values-v8.4.yaml"}'
          VARS_8_5: '{"camunda-helm-git-ref": "main", "extra-values-url": "https://raw.githubusercontent.com/camunda/camunda-platform-helm/main/charts/camunda-platform/values/values-latest.yaml"}'

  get-extra-values:
      needs: determine-inputs
      if: ${{ needs.determine-inputs.outputs.extra-values-url != 'null' }}
      runs-on: ubuntu-latest
      steps:
        - name: HTTP Request Action
          id: extra-values-content
          uses: fjogeleit/http-request-action@v1.15.5
          with:
            url: ${{ needs.process_version.outputs.extra-values-url }}
        - name: WIP Take HTTP response and convert into a .yaml file
          run: |
            echo ${{ steps.extra-values-content.outputs.response }}
            echo ${{ steps.extra-values-content.outputs.headers }}
            echo ${{ steps.extra-values-content.outputs.status }}
        - name: WIP Take YAML file from last step and delete the connectors value
          uses: mikefarah/yq@v4.44.1
          # hint: https://github.com/marketplace/actions/yq-portable-yaml-processor#github-action
        -



  helm-deploy:
    name: Helm chart Integration Tests
    uses: camunda/camunda-platform-helm/.github/workflows/test-integration-template.yaml@main
    secrets: inherit
    with:
      identifier: connectors-int
      test-enabled: true
      extra-values: |
        connectors:
          image:
            tag: ${{ github.event.inputs.connectors_version }}
