
name: Integration test

on:
  workflow_dispatch:
    inputs:
      connectors_version:
        description: 'The version of the connectors to test'
        required: true
        default: 'SNAPSHOT'

defaults:
  run:
    # use bash shell by default to ensure pipefail behavior is the default
    # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

jobs:
  helm-deploy:
    name: Helm chart Integration Tests
    uses: camunda/camunda-platform-helm/.github/workflows/test-integration-template.yaml@main
    secrets: inherit
    with:
      camunda-helm-git-ref: camunda-platform-8.3
      identifier: connectors-int
      test-enabled: true
      extra-values: |
        global:
          image:
            tag: 8.3.10
        identity:
          keycloak:
            # https://hub.docker.com/r/bitnami/keycloak/tags
            image:
              repository: bitnami/keycloak
              tag: 22.0.5
            postgresql:
              # https://hub.docker.com/r/bitnami/postgresql/tags
              image:
                repository: bitnami/postgresql
                tag: 15.5.0
        optimize:
          # https://hub.docker.com/r/camunda/optimize/tags
          image:
            repository: camunda/optimize
            # renovate: datasource=docker depName=camunda/optimize
            tag: 8.3.8
        webModeler:
          # Camunda Enterprise repository.
          # registry.camunda.cloud/web-modeler-ee
          image:
            # renovate: datasource=docker depName=camunda/web-modeler lookupName=registry.camunda.cloud/web-modeler-ee/modeler-restapi
            tag: 8.3.6
        elasticsearch:
          # https://hub.docker.com/r/bitnami/elasticsearch/tags
          image:
            repository: bitnami/elasticsearch
            tag: 8.8.2
        connectors:
          image:
            tag: ${{ github.event.inputs.connectors_version }}
