name: Run uniquet and push
on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'The branch name to run the workflow on'
        required: true
        default: 'main'

jobs:
  run-uniquet-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch_name }}

      - name: install-uniquet
        run: |
          mvn install -pl element-template-generator/uniquet -am

      - name: run-uniquet
        run: |
          BRANCH_NAME=${{ github.event.inputs.branch_name }}
          ./element-template-generator/uniquet/target/appassembler/bin/uniquet --destination ./connector-templates.json --branch $BRANCH_NAME

      - name: Commit connectors template file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -am "ci: adding connectors template file"
          git push --force-with-lease