name: Example Workflow for Testing with Draft PR
on:
  pull_request:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}
          fetch-depth: 0

      - name: Access TAG NAME result
        id: tag_name
        run: echo "curr_tag=8.5.0-alpha1-rc1" >> $GITHUB_OUTPUT


      - name: Validate release tag and determine previous tag
        id: validate_tag
        run: |
          OUTPUT="$(.github/workflows/scripts/prev_tag.sh ${{ steps.tag_name.outputs.curr_tag }})"
          if [ $? -ne 0 ]; then
            echo "Script failed"
            exit 1
          fi
          echo "type=$( echo $OUTPUT | cut -d ' ' -f1 )" >> $GITHUB_OUTPUT
          echo "previousTag=$( echo $OUTPUT | cut -d ' ' -f2 )" >> $GITHUB_OUTPUT

      - name: Build Changelog
        id: changelog
        uses: Requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ steps.tag_name.outputs.curr_tag }}
          toTag: ${{ steps.validate_tag.outputs.previousTag }}
          writeToFile: false
          excludeTypes: build,docs,other,style,ci
          excludeScopes: deps

      - name: Output Release Tag
        run: echo "${{ github.event.release.tag_name }}"

      - name: Output Changelog
        run: echo "${{ steps.changelog.outputs.changes }}"
